### ISSUE TITLE
System.TypeInitializationException from fusillade in win7 / VS 2015 environment

### ISSUE THREAD

**Issue by haamaanaa** [paulcbetts/Fusillade#19]
Same code breaks in Win10 /VS 2015 environment as well. On some machines (whether win 7 or 10), code wokrs fine.

Seems that similar reference issues have been earlier as well:
System.IO.FileNotFoundException: Could not load file or assembly 'Splat, Version=0.0.0.0

[error.txt](https://github.com/paulcbetts/Fusillade/files/251952/error.txt)

**Comment by haamaanaa** [comment]
ari [15:41] 
Error truck:    at Fusillade.NetCache.get_OperationQueue()
  at Fusillade.RateLimitedHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in c:\Users\paul\code\paulcbetts\Fusillade\Fusillade\RateLimitedHttpMessageHandler.cs:line 95
  at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
  at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
  at Refit.RequestBuilderImplementation.<>c__DisplayClass2e`1.<<buildCancellableTaskFuncForMethod>b__2d>d__30.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

**Comment by haamaanaa** [comment]
problem has something to do with Microsoft.CodeDom.Providers.DotNetCompilerPlatform

`    <system.codedom>
        <compilers>
            <compiler language="c#;cs;csharp" extension=".cs" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:6 /nowarn:1659;1699;1701" />
            <compiler language="vb;vbs;visualbasic;vbscript" extension=".vb" type="Microsoft.CodeDom.Providers.DotNetCompilerPlatform.VBCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" warningLevel="4" compilerOptions="/langversion:14 /nowarn:41008 /define:_MYTYPE=\&quot;Web\&quot; /optionInfer+" />
        </compilers>
    </system.codedom>`

**Comment by haamaanaa** [comment]
Problem solved!

Error was caused by missing Splat.dll file in ASP.NET web project's bin folder 

"System.TypeInitializationException: The type initializer for 'Fusillade.NetCache' threw an exception. ---> 
System.IO.FileNotFoundException: Could not load file or assembly 
'Splat, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. 
The system cannot find the file specified."
